/**
 * The catalogue of themes and reading fonts.
 *
 * The colours of the well-known palettes are each project's official ones;
 * what is a choice here is mapping them onto the roles this viewer has
 * (background, accent, keyword…). Every theme declares ALL the keys — one
 * missing would let the previous theme's colour leak through in silence.
 */

export const COLOR_KEYS = [
  "bg",
  "text",
  "muted",
  "border",
  "surface",
  "accent",
  "code-bg",
  "canvas-bg",
  "canvas-grid",
  "code-comment",
  "code-keyword",
  "code-string",
  "code-number",
  "code-function",
  "code-meta",
  "code-type",
] as const;

export type ColorKey = (typeof COLOR_KEYS)[number];

export interface Theme {
  id: string;
  name: string;
  mode: "light" | "dark";
  colors: Record<ColorKey, string>;
}

export const DEFAULT_THEME = "paper";

export const THEMES: Theme[] = [
  {
    id: "paper",
    name: "Paper",
    mode: "light",
    colors: {
      bg: "#fbfaf8",
      text: "#1c1b19",
      muted: "#615e58",
      border: "#e5e1da",
      surface: "#ffffff",
      accent: "#b4441f",
      "code-bg": "#f3f0ea",
      "canvas-bg": "#d5d8db",
      "canvas-grid": "#c3c7cb",
      "code-comment": "#6f6960",
      "code-keyword": "#a03e00",
      "code-string": "#4a7c2f",
      "code-number": "#b4441f",
      "code-function": "#2563a8",
      "code-meta": "#7b4fa8",
      "code-type": "#1a6b6b",
    },
  },
  {
    id: "paper-dark",
    name: "Paper Dark",
    mode: "dark",
    colors: {
      bg: "#161513",
      text: "#e8e5df",
      muted: "#a09a92",
      border: "#2c2a27",
      surface: "#1e1d1a",
      accent: "#e8814f",
      "code-bg": "#22201d",
      "canvas-bg": "#34383c",
      "canvas-grid": "#43484d",
      "code-comment": "#8d867c",
      "code-keyword": "#e8814f",
      "code-string": "#9ccc7c",
      "code-number": "#f0a878",
      "code-function": "#7fb3e8",
      "code-meta": "#c9a0ea",
      "code-type": "#5fc9c9",
    },
  },
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    mode: "light",
    colors: {
      bg: "#eff1f5",
      text: "#4c4f69",
      muted: "#5c5f77",
      border: "#ccd0da",
      surface: "#ffffff",
      accent: "#d20f39",
      "code-bg": "#e6e9ef",
      "canvas-bg": "#ccd0da",
      "canvas-grid": "#bcc0cc",
      "code-comment": "#6c6f85",
      "code-keyword": "#8839ef",
      "code-string": "#40a02b",
      "code-number": "#fe640b",
      "code-function": "#1e66f5",
      "code-meta": "#ea76cb",
      "code-type": "#179299",
    },
  },
  {
    id: "catppuccin-frappe",
    name: "Catppuccin Frappé",
    mode: "dark",
    colors: {
      bg: "#303446",
      text: "#c6d0f5",
      muted: "#a5adce",
      border: "#414559",
      surface: "#292c3c",
      accent: "#e78284",
      "code-bg": "#292c3c",
      "canvas-bg": "#414559",
      "canvas-grid": "#51576d",
      "code-comment": "#838ba7",
      "code-keyword": "#ca9ee6",
      "code-string": "#a6d189",
      "code-number": "#ef9f76",
      "code-function": "#8caaee",
      "code-meta": "#f4b8e4",
      "code-type": "#81c8be",
    },
  },
  {
    id: "catppuccin-macchiato",
    name: "Catppuccin Macchiato",
    mode: "dark",
    colors: {
      bg: "#24273a",
      text: "#cad3f5",
      muted: "#a5adcb",
      border: "#363a4f",
      surface: "#1e2030",
      accent: "#ed8796",
      "code-bg": "#1e2030",
      "canvas-bg": "#363a4f",
      "canvas-grid": "#494d64",
      "code-comment": "#8087a2",
      "code-keyword": "#c6a0f6",
      "code-string": "#a6da95",
      "code-number": "#f5a97f",
      "code-function": "#8aadf4",
      "code-meta": "#f5bde6",
      "code-type": "#8bd5ca",
    },
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    mode: "dark",
    colors: {
      bg: "#1e1e2e",
      text: "#cdd6f4",
      muted: "#a6adc8",
      border: "#313244",
      surface: "#181825",
      accent: "#f38ba8",
      "code-bg": "#181825",
      "canvas-bg": "#313244",
      "canvas-grid": "#45475a",
      "code-comment": "#7f849c",
      "code-keyword": "#cba6f7",
      "code-string": "#a6e3a1",
      "code-number": "#fab387",
      "code-function": "#89b4fa",
      "code-meta": "#f5c2e7",
      "code-type": "#94e2d5",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    mode: "dark",
    colors: {
      bg: "#282a36",
      text: "#f8f8f2",
      muted: "#9ba3c9",
      border: "#44475a",
      surface: "#21222c",
      accent: "#ff79c6",
      "code-bg": "#21222c",
      "canvas-bg": "#44475a",
      "canvas-grid": "#565973",
      "code-comment": "#8b9ad4",
      "code-keyword": "#ff79c6",
      "code-string": "#f1fa8c",
      "code-number": "#bd93f9",
      "code-function": "#50fa7b",
      "code-meta": "#ffb86c",
      "code-type": "#8be9fd",
    },
  },
  {
    id: "nord",
    name: "Nord",
    mode: "dark",
    colors: {
      bg: "#2e3440",
      text: "#eceff4",
      muted: "#b5bdcc",
      border: "#3b4252",
      surface: "#292e39",
      accent: "#88c0d0",
      "code-bg": "#292e39",
      "canvas-bg": "#3b4252",
      "canvas-grid": "#434c5e",
      "code-comment": "#93a1b5",
      "code-keyword": "#81a1c1",
      "code-string": "#a3be8c",
      "code-number": "#b48ead",
      "code-function": "#88c0d0",
      "code-meta": "#d08770",
      "code-type": "#8fbcbb",
    },
  },
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    mode: "dark",
    colors: {
      bg: "#282828",
      text: "#ebdbb2",
      muted: "#bdae93",
      border: "#3c3836",
      surface: "#1d2021",
      accent: "#fe8019",
      "code-bg": "#1d2021",
      "canvas-bg": "#3c3836",
      "canvas-grid": "#504945",
      "code-comment": "#a89984",
      "code-keyword": "#fb4934",
      "code-string": "#b8bb26",
      "code-number": "#d3869b",
      "code-function": "#8ec07c",
      "code-meta": "#fabd2f",
      "code-type": "#83a598",
    },
  },
  {
    id: "gruvbox-light",
    name: "Gruvbox Light",
    mode: "light",
    colors: {
      bg: "#fbf1c7",
      text: "#3c3836",
      muted: "#6d6155",
      border: "#ebdbb2",
      surface: "#f9f5d7",
      accent: "#af3a03",
      "code-bg": "#f2e5bc",
      "canvas-bg": "#ebdbb2",
      "canvas-grid": "#d5c4a1",
      "code-comment": "#6f6558",
      "code-keyword": "#9d0006",
      "code-string": "#79740e",
      "code-number": "#8f3f71",
      "code-function": "#427b58",
      "code-meta": "#b57614",
      "code-type": "#076678",
    },
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    mode: "light",
    colors: {
      bg: "#fdf6e3",
      text: "#073642",
      muted: "#5f7276",
      border: "#eee8d5",
      surface: "#fffbf0",
      accent: "#cb4b16",
      "code-bg": "#eee8d5",
      "canvas-bg": "#eee8d5",
      "canvas-grid": "#ddd6c1",
      "code-comment": "#6a7c80",
      "code-keyword": "#859900",
      "code-string": "#2aa198",
      "code-number": "#d33682",
      "code-function": "#268bd2",
      "code-meta": "#b58900",
      "code-type": "#6c71c4",
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    mode: "dark",
    colors: {
      bg: "#002b36",
      text: "#eee8d5",
      muted: "#93a1a1",
      border: "#073642",
      surface: "#01313d",
      accent: "#cb4b16",
      "code-bg": "#073642",
      "canvas-bg": "#073642",
      "canvas-grid": "#0e4552",
      "code-comment": "#8b9c9c",
      "code-keyword": "#859900",
      "code-string": "#2aa198",
      "code-number": "#d33682",
      "code-function": "#268bd2",
      "code-meta": "#b58900",
      "code-type": "#6c71c4",
    },
  },
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    mode: "dark",
    colors: {
      bg: "#1a1b26",
      text: "#c0caf5",
      muted: "#9aa5ce",
      border: "#292e42",
      surface: "#16161e",
      accent: "#bb9af7",
      "code-bg": "#16161e",
      "canvas-bg": "#292e42",
      "canvas-grid": "#3b4261",
      "code-comment": "#7982a9",
      "code-keyword": "#bb9af7",
      "code-string": "#9ece6a",
      "code-number": "#ff9e64",
      "code-function": "#7aa2f7",
      "code-meta": "#e0af68",
      "code-type": "#7dcfff",
    },
  },
  {
    id: "one-dark",
    name: "One Dark",
    mode: "dark",
    colors: {
      bg: "#282c34",
      text: "#dcdfe4",
      muted: "#9da5b4",
      border: "#3e4451",
      surface: "#21252b",
      accent: "#e06c75",
      "code-bg": "#21252b",
      "canvas-bg": "#3e4451",
      "canvas-grid": "#4b5263",
      "code-comment": "#8b93a1",
      "code-keyword": "#c678dd",
      "code-string": "#98c379",
      "code-number": "#d19a66",
      "code-function": "#61afef",
      "code-meta": "#e5c07b",
      "code-type": "#56b6c2",
    },
  },
  {
    id: "rose-pine",
    name: "Rosé Pine",
    mode: "dark",
    colors: {
      bg: "#191724",
      text: "#e0def4",
      muted: "#a7a3c0",
      border: "#26233a",
      surface: "#1f1d2e",
      accent: "#ebbcba",
      "code-bg": "#1f1d2e",
      "canvas-bg": "#26233a",
      "canvas-grid": "#403d52",
      "code-comment": "#8e8aa8",
      "code-keyword": "#c4a7e7",
      "code-string": "#f6c177",
      "code-number": "#eb6f92",
      "code-function": "#9ccfd8",
      "code-meta": "#ebbcba",
      "code-type": "#31a5c4",
    },
  },
  {
    id: "rose-pine-dawn",
    name: "Rosé Pine Dawn",
    mode: "light",
    colors: {
      bg: "#faf4ed",
      text: "#575279",
      muted: "#6a6484",
      border: "#dfdad9",
      surface: "#fffaf3",
      accent: "#b4637a",
      "code-bg": "#f2e9e1",
      "canvas-bg": "#dfdad9",
      "canvas-grid": "#cecacd",
      "code-comment": "#71708a",
      "code-keyword": "#907aa9",
      "code-string": "#286983",
      "code-number": "#b4637a",
      "code-function": "#56949f",
      "code-meta": "#ea9d34",
      "code-type": "#286983",
    },
  },
  {
    id: "everforest",
    name: "Everforest",
    mode: "dark",
    colors: {
      bg: "#2d353b",
      text: "#d3c6aa",
      muted: "#a6b0a0",
      border: "#3d484d",
      surface: "#272e33",
      accent: "#e69875",
      "code-bg": "#272e33",
      "canvas-bg": "#3d484d",
      "canvas-grid": "#4f585e",
      "code-comment": "#95a08e",
      "code-keyword": "#e67e80",
      "code-string": "#a7c080",
      "code-number": "#d699b6",
      "code-function": "#7fbbb3",
      "code-meta": "#dbbc7f",
      "code-type": "#83c092",
    },
  },
  {
    id: "monokai",
    name: "Monokai",
    mode: "dark",
    colors: {
      bg: "#272822",
      text: "#f8f8f2",
      muted: "#a6a28c",
      border: "#3e3d32",
      surface: "#1e1f1c",
      accent: "#f92672",
      "code-bg": "#1e1f1c",
      "canvas-bg": "#3e3d32",
      "canvas-grid": "#4d4c41",
      "code-comment": "#9b957c",
      "code-keyword": "#f92672",
      "code-string": "#e6db74",
      "code-number": "#ae81ff",
      "code-function": "#a6e22e",
      "code-meta": "#fd971f",
      "code-type": "#66d9ef",
    },
  },
];

export interface Font {
  id: string;
  name: string;
  stack: string;
}

/**
 * The font applies to the lesson TEXT, not to the interface: menu and buttons
 * stay on the system sans-serif. Switching the menu along with it changes the
 * weight of the whole page and gets in the way instead of helping.
 */
export const FONTS: Font[] = [
  {
    id: "serif",
    name: "Serif",
    stack: 'Charter, "Bitstream Charter", "Iowan Old Style", "Palatino Linotype", Georgia, serif',
  },
  {
    id: "sans",
    name: "Sans serif",
    stack: 'ui-sans-serif, -apple-system, "Segoe UI", system-ui, sans-serif',
  },
  {
    id: "humanist",
    name: "Humanist",
    stack: 'Optima, Candara, "Gill Sans", "Trebuchet MS", sans-serif',
  },
];

export const DEFAULT_FONT = "serif";

const block = (selector: string, colors: Record<string, string>) =>
  `${selector} {\n${Object.entries(colors)
    .map(([k, v]) => `    --${k}: ${v};`)
    .join("\n")}\n  }`;

/** One block per theme, addressed by `data-theme` on the root element. */
export function themeCss(): string {
  const fallback = THEMES.find((t) => t.id === DEFAULT_THEME)!;

  const parts = [
    `  /* the default, in force before any choice is made */\n  ${block(":root", fallback.colors)}`,
    ...THEMES.map((t) => `  ${block(`:root[data-theme="${t.id}"]`, t.colors)}`),
    ...FONTS.map((f) => `  :root[data-font="${f.id}"] main { --reading-font: ${f.stack}; }`),
  ];

  return parts.join("\n");
}
