/**
 * Catálogo de temas e fontes do viewer.
 *
 * As cores das paletas famosas são as oficiais de cada projeto; o que é
 * escolha minha é o mapeamento delas para os papéis daqui (fundo, destaque,
 * palavra-chave…). Todo tema declara TODAS as chaves — faltar uma faria a cor
 * vazar do tema anterior em silêncio.
 */

export const CHAVES_DE_COR = [
  "fundo",
  "texto",
  "suave",
  "linha",
  "caixa",
  "destaque",
  "codigo",
  "desenho-fundo",
  "desenho-grade",
  "cod-comentario",
  "cod-chave",
  "cod-texto",
  "cod-numero",
  "cod-funcao",
  "cod-meta",
  "cod-tipo",
] as const;

export type ChaveDeCor = (typeof CHAVES_DE_COR)[number];

export interface Tema {
  id: string;
  nome: string;
  brilho: "claro" | "escuro";
  cores: Record<ChaveDeCor, string>;
}

export const TEMA_PADRAO = "papel";

export const TEMAS: Tema[] = [
  {
    id: "papel",
    nome: "Papel",
    brilho: "claro",
    cores: {
      fundo: "#fbfaf8",
      texto: "#1c1b19",
      suave: "#615e58",
      linha: "#e5e1da",
      caixa: "#ffffff",
      destaque: "#b4441f",
      codigo: "#f3f0ea",
      "desenho-fundo": "#d5d8db",
      "desenho-grade": "#c3c7cb",
      "cod-comentario": "#6f6960",
      "cod-chave": "#a03e00",
      "cod-texto": "#4a7c2f",
      "cod-numero": "#b4441f",
      "cod-funcao": "#2563a8",
      "cod-meta": "#7b4fa8",
      "cod-tipo": "#1a6b6b",
    },
  },
  {
    id: "papel-escuro",
    nome: "Papel escuro",
    brilho: "escuro",
    cores: {
      fundo: "#161513",
      texto: "#e8e5df",
      suave: "#a09a92",
      linha: "#2c2a27",
      caixa: "#1e1d1a",
      destaque: "#e8814f",
      codigo: "#22201d",
      "desenho-fundo": "#34383c",
      "desenho-grade": "#43484d",
      "cod-comentario": "#8d867c",
      "cod-chave": "#e8814f",
      "cod-texto": "#9ccc7c",
      "cod-numero": "#f0a878",
      "cod-funcao": "#7fb3e8",
      "cod-meta": "#c9a0ea",
      "cod-tipo": "#5fc9c9",
    },
  },
  {
    id: "catppuccin-latte",
    nome: "Catppuccin Latte",
    brilho: "claro",
    cores: {
      fundo: "#eff1f5",
      texto: "#4c4f69",
      suave: "#5c5f77",
      linha: "#ccd0da",
      caixa: "#ffffff",
      destaque: "#d20f39",
      codigo: "#e6e9ef",
      "desenho-fundo": "#ccd0da",
      "desenho-grade": "#bcc0cc",
      "cod-comentario": "#6c6f85",
      "cod-chave": "#8839ef",
      "cod-texto": "#40a02b",
      "cod-numero": "#fe640b",
      "cod-funcao": "#1e66f5",
      "cod-meta": "#ea76cb",
      "cod-tipo": "#179299",
    },
  },
  {
    id: "catppuccin-frappe",
    nome: "Catppuccin Frappé",
    brilho: "escuro",
    cores: {
      fundo: "#303446",
      texto: "#c6d0f5",
      suave: "#a5adce",
      linha: "#414559",
      caixa: "#292c3c",
      destaque: "#e78284",
      codigo: "#292c3c",
      "desenho-fundo": "#414559",
      "desenho-grade": "#51576d",
      "cod-comentario": "#838ba7",
      "cod-chave": "#ca9ee6",
      "cod-texto": "#a6d189",
      "cod-numero": "#ef9f76",
      "cod-funcao": "#8caaee",
      "cod-meta": "#f4b8e4",
      "cod-tipo": "#81c8be",
    },
  },
  {
    id: "catppuccin-macchiato",
    nome: "Catppuccin Macchiato",
    brilho: "escuro",
    cores: {
      fundo: "#24273a",
      texto: "#cad3f5",
      suave: "#a5adcb",
      linha: "#363a4f",
      caixa: "#1e2030",
      destaque: "#ed8796",
      codigo: "#1e2030",
      "desenho-fundo": "#363a4f",
      "desenho-grade": "#494d64",
      "cod-comentario": "#8087a2",
      "cod-chave": "#c6a0f6",
      "cod-texto": "#a6da95",
      "cod-numero": "#f5a97f",
      "cod-funcao": "#8aadf4",
      "cod-meta": "#f5bde6",
      "cod-tipo": "#8bd5ca",
    },
  },
  {
    id: "catppuccin-mocha",
    nome: "Catppuccin Mocha",
    brilho: "escuro",
    cores: {
      fundo: "#1e1e2e",
      texto: "#cdd6f4",
      suave: "#a6adc8",
      linha: "#313244",
      caixa: "#181825",
      destaque: "#f38ba8",
      codigo: "#181825",
      "desenho-fundo": "#313244",
      "desenho-grade": "#45475a",
      "cod-comentario": "#7f849c",
      "cod-chave": "#cba6f7",
      "cod-texto": "#a6e3a1",
      "cod-numero": "#fab387",
      "cod-funcao": "#89b4fa",
      "cod-meta": "#f5c2e7",
      "cod-tipo": "#94e2d5",
    },
  },
  {
    id: "dracula",
    nome: "Dracula",
    brilho: "escuro",
    cores: {
      fundo: "#282a36",
      texto: "#f8f8f2",
      suave: "#9ba3c9",
      linha: "#44475a",
      caixa: "#21222c",
      destaque: "#ff79c6",
      codigo: "#21222c",
      "desenho-fundo": "#44475a",
      "desenho-grade": "#565973",
      "cod-comentario": "#8b9ad4",
      "cod-chave": "#ff79c6",
      "cod-texto": "#f1fa8c",
      "cod-numero": "#bd93f9",
      "cod-funcao": "#50fa7b",
      "cod-meta": "#ffb86c",
      "cod-tipo": "#8be9fd",
    },
  },
  {
    id: "nord",
    nome: "Nord",
    brilho: "escuro",
    cores: {
      fundo: "#2e3440",
      texto: "#eceff4",
      suave: "#b5bdcc",
      linha: "#3b4252",
      caixa: "#292e39",
      destaque: "#88c0d0",
      codigo: "#292e39",
      "desenho-fundo": "#3b4252",
      "desenho-grade": "#434c5e",
      "cod-comentario": "#93a1b5",
      "cod-chave": "#81a1c1",
      "cod-texto": "#a3be8c",
      "cod-numero": "#b48ead",
      "cod-funcao": "#88c0d0",
      "cod-meta": "#d08770",
      "cod-tipo": "#8fbcbb",
    },
  },
  {
    id: "gruvbox-escuro",
    nome: "Gruvbox escuro",
    brilho: "escuro",
    cores: {
      fundo: "#282828",
      texto: "#ebdbb2",
      suave: "#bdae93",
      linha: "#3c3836",
      caixa: "#1d2021",
      destaque: "#fe8019",
      codigo: "#1d2021",
      "desenho-fundo": "#3c3836",
      "desenho-grade": "#504945",
      "cod-comentario": "#a89984",
      "cod-chave": "#fb4934",
      "cod-texto": "#b8bb26",
      "cod-numero": "#d3869b",
      "cod-funcao": "#8ec07c",
      "cod-meta": "#fabd2f",
      "cod-tipo": "#83a598",
    },
  },
  {
    id: "gruvbox-claro",
    nome: "Gruvbox claro",
    brilho: "claro",
    cores: {
      fundo: "#fbf1c7",
      texto: "#3c3836",
      suave: "#6d6155",
      linha: "#ebdbb2",
      caixa: "#f9f5d7",
      destaque: "#af3a03",
      codigo: "#f2e5bc",
      "desenho-fundo": "#ebdbb2",
      "desenho-grade": "#d5c4a1",
      "cod-comentario": "#6f6558",
      "cod-chave": "#9d0006",
      "cod-texto": "#79740e",
      "cod-numero": "#8f3f71",
      "cod-funcao": "#427b58",
      "cod-meta": "#b57614",
      "cod-tipo": "#076678",
    },
  },
  {
    id: "solarized-claro",
    nome: "Solarized claro",
    brilho: "claro",
    cores: {
      fundo: "#fdf6e3",
      texto: "#073642",
      suave: "#5f7276",
      linha: "#eee8d5",
      caixa: "#fffbf0",
      destaque: "#cb4b16",
      codigo: "#eee8d5",
      "desenho-fundo": "#eee8d5",
      "desenho-grade": "#ddd6c1",
      "cod-comentario": "#6a7c80",
      "cod-chave": "#859900",
      "cod-texto": "#2aa198",
      "cod-numero": "#d33682",
      "cod-funcao": "#268bd2",
      "cod-meta": "#b58900",
      "cod-tipo": "#6c71c4",
    },
  },
  {
    id: "solarized-escuro",
    nome: "Solarized escuro",
    brilho: "escuro",
    cores: {
      fundo: "#002b36",
      texto: "#eee8d5",
      suave: "#93a1a1",
      linha: "#073642",
      caixa: "#01313d",
      destaque: "#cb4b16",
      codigo: "#073642",
      "desenho-fundo": "#073642",
      "desenho-grade": "#0e4552",
      "cod-comentario": "#8b9c9c",
      "cod-chave": "#859900",
      "cod-texto": "#2aa198",
      "cod-numero": "#d33682",
      "cod-funcao": "#268bd2",
      "cod-meta": "#b58900",
      "cod-tipo": "#6c71c4",
    },
  },
  {
    id: "tokyo-night",
    nome: "Tokyo Night",
    brilho: "escuro",
    cores: {
      fundo: "#1a1b26",
      texto: "#c0caf5",
      suave: "#9aa5ce",
      linha: "#292e42",
      caixa: "#16161e",
      destaque: "#bb9af7",
      codigo: "#16161e",
      "desenho-fundo": "#292e42",
      "desenho-grade": "#3b4261",
      "cod-comentario": "#7982a9",
      "cod-chave": "#bb9af7",
      "cod-texto": "#9ece6a",
      "cod-numero": "#ff9e64",
      "cod-funcao": "#7aa2f7",
      "cod-meta": "#e0af68",
      "cod-tipo": "#7dcfff",
    },
  },
  {
    id: "one-dark",
    nome: "One Dark",
    brilho: "escuro",
    cores: {
      fundo: "#282c34",
      texto: "#dcdfe4",
      suave: "#9da5b4",
      linha: "#3e4451",
      caixa: "#21252b",
      destaque: "#e06c75",
      codigo: "#21252b",
      "desenho-fundo": "#3e4451",
      "desenho-grade": "#4b5263",
      "cod-comentario": "#8b93a1",
      "cod-chave": "#c678dd",
      "cod-texto": "#98c379",
      "cod-numero": "#d19a66",
      "cod-funcao": "#61afef",
      "cod-meta": "#e5c07b",
      "cod-tipo": "#56b6c2",
    },
  },
  {
    id: "rose-pine",
    nome: "Rosé Pine",
    brilho: "escuro",
    cores: {
      fundo: "#191724",
      texto: "#e0def4",
      suave: "#a7a3c0",
      linha: "#26233a",
      caixa: "#1f1d2e",
      destaque: "#ebbcba",
      codigo: "#1f1d2e",
      "desenho-fundo": "#26233a",
      "desenho-grade": "#403d52",
      "cod-comentario": "#8e8aa8",
      "cod-chave": "#c4a7e7",
      "cod-texto": "#f6c177",
      "cod-numero": "#eb6f92",
      "cod-funcao": "#9ccfd8",
      "cod-meta": "#ebbcba",
      "cod-tipo": "#31a5c4",
    },
  },
  {
    id: "rose-pine-dawn",
    nome: "Rosé Pine Dawn",
    brilho: "claro",
    cores: {
      fundo: "#faf4ed",
      texto: "#575279",
      suave: "#6a6484",
      linha: "#dfdad9",
      caixa: "#fffaf3",
      destaque: "#b4637a",
      codigo: "#f2e9e1",
      "desenho-fundo": "#dfdad9",
      "desenho-grade": "#cecacd",
      "cod-comentario": "#71708a",
      "cod-chave": "#907aa9",
      "cod-texto": "#286983",
      "cod-numero": "#b4637a",
      "cod-funcao": "#56949f",
      "cod-meta": "#ea9d34",
      "cod-tipo": "#286983",
    },
  },
  {
    id: "everforest",
    nome: "Everforest",
    brilho: "escuro",
    cores: {
      fundo: "#2d353b",
      texto: "#d3c6aa",
      suave: "#a6b0a0",
      linha: "#3d484d",
      caixa: "#272e33",
      destaque: "#e69875",
      codigo: "#272e33",
      "desenho-fundo": "#3d484d",
      "desenho-grade": "#4f585e",
      "cod-comentario": "#95a08e",
      "cod-chave": "#e67e80",
      "cod-texto": "#a7c080",
      "cod-numero": "#d699b6",
      "cod-funcao": "#7fbbb3",
      "cod-meta": "#dbbc7f",
      "cod-tipo": "#83c092",
    },
  },
  {
    id: "monokai",
    nome: "Monokai",
    brilho: "escuro",
    cores: {
      fundo: "#272822",
      texto: "#f8f8f2",
      suave: "#a6a28c",
      linha: "#3e3d32",
      caixa: "#1e1f1c",
      destaque: "#f92672",
      codigo: "#1e1f1c",
      "desenho-fundo": "#3e3d32",
      "desenho-grade": "#4d4c41",
      "cod-comentario": "#9b957c",
      "cod-chave": "#f92672",
      "cod-texto": "#e6db74",
      "cod-numero": "#ae81ff",
      "cod-funcao": "#a6e22e",
      "cod-meta": "#fd971f",
      "cod-tipo": "#66d9ef",
    },
  },
];

export interface Fonte {
  id: string;
  nome: string;
  pilha: string;
}

/**
 * A fonte vale para o TEXTO da lição, não para a interface: menu e botões
 * ficam sempre na sem-serifa do sistema. Trocar a fonte do menu junto muda o
 * peso da página inteira e atrapalha em vez de ajudar.
 */
export const FONTES: Fonte[] = [
  {
    id: "serifada",
    nome: "Serifada",
    pilha: 'Charter, "Bitstream Charter", "Iowan Old Style", "Palatino Linotype", Georgia, serif',
  },
  {
    id: "sem-serifa",
    nome: "Sem serifa",
    pilha: 'ui-sans-serif, -apple-system, "Segoe UI", system-ui, sans-serif',
  },
  {
    id: "humanista",
    nome: "Humanista",
    pilha: 'Optima, Candara, "Gill Sans", "Trebuchet MS", sans-serif',
  },
];

export const FONTE_PADRAO = "serifada";

const bloco = (seletor: string, cores: Record<string, string>) =>
  `${seletor} {\n${Object.entries(cores)
    .map(([k, v]) => `    --${k}: ${v};`)
    .join("\n")}\n  }`;

/** Um bloco por tema, endereçado por `data-tema` na raiz. */
export function cssDosTemas(): string {
  const padrao = TEMAS.find((t) => t.id === TEMA_PADRAO)!;

  const partes = [
    `  /* padrão, valendo antes de qualquer escolha */\n  ${bloco(":root", padrao.cores)}`,
    ...TEMAS.map((t) => `  ${bloco(`:root[data-tema="${t.id}"]`, t.cores)}`),
    ...FONTES.map((f) => `  :root[data-fonte="${f.id}"] main { --fonte-leitura: ${f.pilha}; }`),
  ];

  return partes.join("\n");
}
